on: push

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: get from repository
        uses: actions/checkout@v4

      - name: install dependency
        run: npm install

      - name: project package
        run: npm run build

